{% set name = "rdchiral_cpp" %}
{% set version = "1.1.1" %}
{% set git_version = "d7c228889da3bf55552b87471cc1ea3d4e779448" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/ljn917/rdchiral_cpp/-/archive/{{ git_version }}/rdchiral_cpp-{{ git_version }}.tar.gz
  sha256: 1470fdf0e3b66873cf3e7232cf7865b340594df4764e20ad46e18c97f5fc1986
#   patches:
#     - cmake.patch

build:
  number: 3
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config
  host:
    - python
    - pip
    - rdkit {{ rdkit_version }}
    - boost >=1.67
    - boost-cpp >=1.67
  run:
    - python
    - {{ pin_compatible('rdkit', max_pin='x.x') }}
    - {{ pin_compatible('boost', max_pin='x.x') }}

test:
  imports:
    - rdchiral
  source_files:
    - test/test_rdchiral.py
    - test/test_rdchiral_cases.json
    - test/test_rdchiral2.py
    - test/test_rdchiral3.py
    - test/test_rdchiral4.py
  commands:
    - python test/test_rdchiral.py
    - python test/test_rdchiral3.py
    - python test/test_rdchiral4.py

about:
  home: https://gitlab.com/ljn917/rdchiral_cpp
  license: MIT
  license_file: LICENSE
  summary: 'C++ implementation of rdchiral'

extra:
  recipe-maintainers:
    - hadim
